services:
- docker
env:
  global:
    - GCP_PROJECT_ID=second-terraform-project
    - IMAGE=gcr.io/second-terraform-project/myworld
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=terraform.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"
install: true
script:
  - |-
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    set +x